# Generated by Django 6.0 on 2025-12-23 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Captura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, unique=True)),
                ('temperatura', models.FloatField(help_text='Grados centígrados')),
                ('viento_kmh', models.FloatField(help_text='Velocidad viento km/h')),
                ('precipitacion', models.FloatField(default=0.0, help_text='Lluvia mm')),
                ('codigo_clima', models.IntegerField(help_text='Código WMO')),
                ('es_festivo', models.BooleanField(default=False)),
                ('es_fin_semana', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Estacion',
            fields=[
                ('id', models.IntegerField(help_text='ID oficial de la estación Bizi', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('capacidad_total', models.IntegerField(help_text='Suma de anclajes + bicis')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LecturaEstacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bicis_disponibles', models.IntegerField()),
                ('anclajes_libres', models.IntegerField()),
                ('estado', models.CharField(choices=[('OPN', 'Operativa'), ('CLS', 'Cerrada'), ('BON', 'Solo Bicis')], default='OPN', max_length=3)),
                ('captura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='core.captura')),
                ('estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='core.estacion')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('captura', 'estacion'), name='unique_lectura_por_captura')],
            },
        ),
    ]
