# Generated by Django 6.0 on 2025-12-25 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estacion',
            old_name='id',
            new_name='id_externo',
        ),
    ]
