# Generated by Django 6.0 on 2025-12-25 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_id_estacion_id_externo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacion',
            name='capacidad_total',
            field=models.IntegerField(blank=True, help_text='Suma de anclajes + bicis', null=True),
        ),
    ]
